---
# tasks file for os


- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Include controllers tasks
  ansible.builtin.include_tasks:
    file: controllers.yml
  when: inventory_hostname in groups['controllers']

- name: Include keystone tasks
  ansible.builtin.include_tasks:
    file: keystone.yml
  when: inventory_hostname in groups['controllers']

- name: Include apache tasks
  ansible.builtin.include_tasks:
    file: apache.yml
  when: inventory_hostname in groups['controllers']

- name: Include projects tasks
  ansible.builtin.include_tasks:
    file: projects.yml
  when: inventory_hostname in groups['controllers']

- name: Include glance tasks
  ansible.builtin.include_tasks:
    file: glance.yml
  when: inventory_hostname in groups['controllers']

- name: Include placement tasks
  ansible.builtin.include_tasks:
    file: placement.yml
  when: inventory_hostname in groups['controllers']

- name: Include nova tasks
  ansible.builtin.include_tasks:
    file: nova.yml
  when: inventory_hostname in groups['controllers']

- name: Include neutron tasks
  ansible.builtin.include_tasks:
    file: neutron.yml
  when: inventory_hostname in groups['controllers']

- name: Include OVN tasks
  ansible.builtin.include_tasks:
    file: ovn.yml
  when: inventory_hostname in groups['controllers']

- name: Include nova-compute tasks
  ansible.builtin.include_tasks:
    file: nova_compute.yml
  when: inventory_hostname in groups['compute']

- name: Ensure /etc/hosts entries for all wireguard hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ hostvars[item]['wg_ip'] }}\\s"
    line: "{{ hostvars[item]['wg_ip'] }} {{ item }}"
  loop: "{{ groups['wireguard_mesh'] }}"


- name: Include chrony tasks
  ansible.builtin.include_tasks:
    file: chrony.yml

