---
- name: Create nova user
  ansible.builtin.command:
    cmd: openstack user create --domain default --password {{ nova_pass }} nova
  environment: "{{ os_admin_env }}"
  register: result
  failed_when: result.rc != 0 and "HTTP 409" not in result.stderr
  changed_when: result.rc == 0
  no_log: true

- name: Add nova user to service project with admin role
  ansible.builtin.command:
    cmd: openstack role add --project service --user nova admin
  environment: "{{ os_admin_env }}"
  changed_when: false

- name: Create nova service
  ansible.builtin.command:
    cmd: openstack service create --name nova --description "OpenStack Compute" compute
  environment: "{{ os_admin_env }}"
  register: result
  failed_when: result.rc != 0 and "HTTP 409" not in result.stderr
  changed_when: result.rc == 0

- name: List existing nova endpoints
  ansible.builtin.shell:
    cmd: openstack endpoint list -f value -c "Service Type" -c Interface | awk '/^compute / {print $2}'
  environment: "{{ os_admin_env }}"
  register: nova_endpoints
  changed_when: false

- name: Create nova endpoints
  ansible.builtin.command:
    cmd: openstack endpoint create --region RegionOne compute {{ item }} http://{{ wg_ip }}:8774/v2.1
  environment: "{{ os_admin_env }}"
  loop:
    - public
    - internal
    - admin
  when: item not in nova_endpoints.stdout_lines

- name: Install nova packages
  ansible.builtin.package:
    name:
      - nova-api
      - nova-conductor
      - nova-novncproxy
      - nova-scheduler
    state: present

- name: Configure nova
  ansible.builtin.template:
    src: nova.conf.j2
    dest: /etc/nova/nova.conf
    owner: nova
    group: nova
    mode: "0640"
  notify: Restart nova

- name: Sync nova api database
  ansible.builtin.command:
    cmd: nova-manage api_db sync
  become: true
  become_user: nova
  changed_when: false

- name: Map cell0
  ansible.builtin.command:
    cmd: nova-manage cell_v2 map_cell0
  become: true
  become_user: nova
  changed_when: false

- name: List nova cells
  ansible.builtin.command:
    cmd: nova-manage cell_v2 list_cells
  become: true
  become_user: nova
  register: nova_cells
  changed_when: false

- name: Create nova cell1
  ansible.builtin.command:
    cmd: nova-manage cell_v2 create_cell --name=cell1 --verbose
  become: true
  become_user: nova
  when: "'cell1' not in nova_cells.stdout"

- name: Sync nova database
  ansible.builtin.command:
    cmd: nova-manage db sync
  become: true
  become_user: nova
  changed_when: false
