---
- name: Install OVN packages
  ansible.builtin.package:
    name:
      - ovn-central
      - ovn-host
      - openvswitch-switch
    state: present

- name: Initialize OVN northbound database
  ansible.builtin.command:
    cmd: ovn-nbctl init
  changed_when: false

- name: Initialize OVN southbound database
  ansible.builtin.command:
    cmd: ovn-sbctl init
  changed_when: false

- name: Enable and start ovn-northd
  ansible.builtin.service:
    name: ovn-northd
    state: started
    enabled: true

- name: Set OVN northbound connection
  ansible.builtin.command:
    cmd: ovn-nbctl set-connection ptcp:6641:{{ wg_ip }}
  changed_when: false

- name: Set OVN southbound connection
  ansible.builtin.command:
    cmd: ovn-sbctl set-connection ptcp:6642:{{ wg_ip }}
  changed_when: false

- name: Flush handlers to restart neutron-server before configuring ovn-controller
  ansible.builtin.meta: flush_handlers

- name: Configure OVS for ovn-controller
  ansible.builtin.command:
    cmd: >
      ovs-vsctl set open_vswitch .
      external-ids:ovn-remote=tcp:{{ wg_ip }}:6642
      external-ids:ovn-encap-type=geneve
      external-ids:ovn-encap-ip={{ wg_ip }}
      external-ids:ovn-bridge=br-int
  changed_when: false

- name: Enable and start ovn-host (ovn-controller)
  ansible.builtin.service:
    name: ovn-host
    state: started
    enabled: true
