---
- name: Create placement user
  ansible.builtin.command:
    cmd: openstack user create --domain default --password {{ placement_pass }} placement
  environment: "{{ os_admin_env }}"
  register: result
  failed_when: result.rc != 0 and "HTTP 409" not in result.stderr
  changed_when: result.rc == 0
  no_log: true

- name: Add placement user to service project with admin role
  ansible.builtin.command:
    cmd: openstack role add --project service --user placement admin
  environment: "{{ os_admin_env }}"
  changed_when: false

- name: Create placement service
  ansible.builtin.command:
    cmd: openstack service create --name placement --description "Placement API" placement
  environment: "{{ os_admin_env }}"
  register: result
  failed_when: result.rc != 0 and "HTTP 409" not in result.stderr
  changed_when: result.rc == 0

- name: List existing placement endpoints
  ansible.builtin.shell:
    cmd: openstack endpoint list -f value -c "Service Type" -c Interface | awk '/^placement / {print $2}'
  environment: "{{ os_admin_env }}"
  register: placement_endpoints
  changed_when: false

- name: Create placement endpoints
  ansible.builtin.command:
    cmd: openstack endpoint create --region RegionOne placement {{ item }} http://{{ wg_ip }}:8778
  environment: "{{ os_admin_env }}"
  loop:
    - public
    - internal
    - admin
  when: item not in placement_endpoints.stdout_lines

- name: Install placement-api
  ansible.builtin.package:
    name: placement-api
    state: present

- name: Configure placement
  ansible.builtin.template:
    src: placement.conf.j2
    dest: /etc/placement/placement.conf
    owner: placement
    group: placement
    mode: "0640"
  notify: Restart apache2

- name: Populate placement database
  ansible.builtin.command:
    cmd: placement-manage db sync
  become: true
  become_user: placement
  changed_when: false
