---
all:
  children:
    wireguard_mesh:
      hosts:
        main-hp:
          ansible_host: 100.68.102.106
          wg_ip: 172.16.100.1
          wg_endpoint: 192.168.0.60
          
        hp-01:
          ansible_host: 100.93.75.19
          wg_ip: 172.16.100.2
          wg_endpoint: 192.168.0.50

        hp-02:
          ansible_host: 100.124.102.103
          wg_ip: 172.16.100.3
          wg_endpoint: 192.168.0.55

        main-1:
          ansible_host: 100.117.99.12
          wg_ip: 172.16.100.4
          wg_endpoint: 100.117.99.12

        main-2:
          ansible_host: 100.99.132.72
          wg_ip: 172.16.100.5
          wg_endpoint: 100.99.132.72

    # ── CloudStack management server ──────────────────────────────────────────
    cloudstack_management:
      hosts:
        main-hp:
