---
all:
  children:
    wireguard_mesh:
      hosts:
        main-hp:
          ansible_host: 100.68.102.106
          wg_ip: 172.16.100.1
          wg_endpoint: 192.168.0.60
          vms:
            - {name: main-hp-vm1, ip: 172.16.102.1}
            - {name: main-hp-vm2, ip: 172.16.102.2}

        hp-01:
          ansible_host: 100.93.75.19
          wg_ip: 172.16.100.2
          wg_endpoint: 192.168.0.50
          vms:
            - {name: hp-01-vm1, ip: 172.16.102.3}
            - {name: hp-01-vm2, ip: 172.16.102.4}

        hp-02:
          ansible_host: 100.124.102.103
          wg_ip: 172.16.100.3
          wg_endpoint: 192.168.0.55
          vms:
            - {name: hp-02-vm1, ip: 172.16.102.5}
            - {name: hp-02-vm2, ip: 172.16.102.6}

        main-1:
          ansible_host: 100.117.99.12
          wg_ip: 172.16.100.4
          wg_endpoint: 100.117.99.12
          vms:
            - {name: main-1-vm1, ip: 172.16.102.7}
            - {name: main-1-vm2, ip: 172.16.102.8}

        main-2:
          ansible_host: 100.99.132.72
          wg_ip: 172.16.100.5
          wg_endpoint: 100.99.132.72
          vms:
            - {name: main-2-vm1, ip: 172.16.102.9}
            - {name: main-2-vm2, ip: 172.16.102.10}

    compute:
      hosts:
        hp-01:
        hp-02:
        main-1:
        main-2:
        main-hp:

    openstack_all:
      children:
        openstack_controller:
          hosts:
            controller-vm:
              ansible_host: 172.16.102.1
        openstack_compute:
          hosts:
            compute-vm-1:
              ansible_host: 172.16.102.2
            compute-vm-2:
              ansible_host: 172.16.102.3
            compute-vm-3:
              ansible_host: 172.16.102.4
            compute-vm-4:
              ansible_host: 172.16.102.5
            compute-vm-5:
              ansible_host: 172.16.102.6
            compute-vm-6:
              ansible_host: 172.16.102.7
            compute-vm-7:
              ansible_host: 172.16.102.8
            compute-vm-8:
              ansible_host: 172.16.102.9
            compute-vm-9:
              ansible_host: 172.16.102.10
