#SPDX-License-Identifier: MIT-0
---
# handlers file for os

- name: Restart chrony
  ansible.builtin.service:
    name: chrony
    state: restarted
    enabled: true

- name: Restart rabbitmq
  ansible.builtin.service:
    name: rabbitmq-server
    state: restarted
    enabled: true

- name: Restart mariadb
  ansible.builtin.service:
    name: mariadb
    state: restarted
    enabled: true

- name: Restart memcached
  ansible.builtin.service:
    name: memcached
    state: restarted
    enabled: true

- name: Restart apache2
  ansible.builtin.service:
    name: apache2
    state: restarted
    enabled: true

- name: Restart glance-api
  ansible.builtin.service:
    name: glance-api
    state: restarted
    enabled: true

- name: Restart nova
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - nova-api
    - nova-scheduler
    - nova-conductor
    - nova-novncproxy

- name: Restart neutron-server
  ansible.builtin.service:
    name: neutron-server
    state: restarted
    enabled: true

- name: Restart nova-compute
  ansible.builtin.service:
    name: nova-compute
    state: restarted
    enabled: true
