---
nfs_exports:
  - path: /export/primary
    size_gb: 400        # Adjust to your available disk on main-hp
    options: "172.16.100.0/24(rw,async,no_root_squash,no_subtree_check)"

  - path: /export/secondary
    size_gb: 200
    options: "172.16.100.0/24(rw,async,no_root_squash,no_subtree_check)"
