---
- name: Install MySQL server
  ansible.builtin.package:
    name:
      - mysql-server
      - python3-pymysql    # Required for Ansible MySQL modules
    state: present

- name: Ensure MySQL is started and enabled
  ansible.builtin.systemd:
    name: mysql
    enabled: true
    state: started

- name: Deploy MySQL CloudStack tuning config
  ansible.builtin.template:
    src: cloudstack.cnf.j2
    dest: /etc/mysql/conf.d/cloudstack.cnf
    owner: root
    group: root
    mode: '0644'
  notify: Restart MySQL

- name: Set MySQL root password
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  no_log: true

- name: Deploy .my.cnf for root
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'

- name: Remove anonymous MySQL users
  community.mysql.mysql_user:
    name: ''
    host_all: true
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Remove MySQL test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create CloudStack database
  community.mysql.mysql_db:
    name: "{{ mysql_cs_database }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create CloudStack DB user
  community.mysql.mysql_user:
    name: "{{ mysql_cs_user }}"
    password: "{{ mysql_cs_password }}"
    priv: "{{ mysql_cs_database }}.*:ALL"
    host: localhost
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
